---
title: "challenge_spls"
author: "Pierre Catoire"
date: "13/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
library(mixOmics)
library(dplyr)
set.seed(301)
```

## Chargement des données

```{r}
load("data_train.rda")
df = data_train
rm(data_train)
nrow(df[is.na(df)])
x = df[1:(length(df)-1)] %>% as.matrix()
remove = c()
for(i in 1:1000){
  if(var(x[,i])==0){
    remove = remove %>% append(i)
  }
}
x = x[,-remove]
y = df[,length(df)] %>% as.factor()

load("data_test.rda")
xtest = data_test %>% as.matrix()
```

```{r}
plsda.res = plsda(x, y, ncomp = 10)
plsda.res
```

```{r}
perf.plsda = perf(plsda.res,
                  validation = "Mfold",
                  folds = 5, 
                  progressBar = T,
                  auc = TRUE,
                  nrepeat = 10)

# perf.plsda.srbct$error.rate  # error rates
plot(perf.plsda,
     col = color.mixo(1:3),
     sd = TRUE,
     legend.position = "horizontal")
```

```{r}
list.keepX <- c(seq(10, 200, 10))
```

```{r}
tune.splsda = tune.splsda(x, y, ncomp = 3, validation = 'Mfold', folds = 5, 
                           progressBar = T, dist = 'max.dist',
                           test.keepX = list.keepX, nrepeat = 10) #nrepeat 50-100 for better estimate

tune.splsda$choice.keepX
tune.splsda$choice.ncomp$ncomp
```

```{r}
choice.ncomp = tune.splsda$choice.ncomp$ncomp
choice.keepX = tune.splsda$choice.keepX[1:choice.ncomp]
## sPLS-DA function
splsda.res = splsda(x, y,
                    ncomp = choice.ncomp,
                    keepX = choice.keepX) # where keepX is the number of variables selected for each components
```

```{r}
perf.splsda = perf(splsda.res, validation = "Mfold", folds = 5, 
                  progressBar = FALSE, auc = TRUE, nrepeat = 10) 

perf.splsda$error.rate
```

```{r}
varsel = selectVar(splsda.res, comp = 1)$value %>% rownames()
```

```{r}
test.predict = predict(splsda.res, xtest[,-remove], dist = "max.dist")
prediction = test.predict$class$max.dist[,1] %>% as.numeric()
prediction

soumission_baseline = c(prediction, varsel)
write(soumission_baseline, file = "baseline.csv")
```

## IGBOOST

##Elasticnet

```{r}
control <- trainControl(method = "repeatedcv",
                              number = 5,
                              repeats = 5,
                              search = "random",
                              verboseIter = TRUE)

elastic_model <- train(y ~ .,
                           data = cbind(x,y),
                           method = "glmnet",
                           preProcess = c("center", "scale"),
                           tuneLength = 25,
                           trControl = control)

predict(elastic_model,newdata = xtest)
```

